version: '3.3'

#services describe the containers that will start
services: 
    # api is the container name for our Go API
    api:
        # It will look for a dockerfile in the project root and build it
        build: "."
        # Exposes the port from a container and binds it to a random port
        ports:
            - "8082"
        # always restart if container goes down
        restart: "always"
        # Connects the API to a common api.network bridge
        networks: 
            - "api.network"
        # Starts up replicas of the same image
        deploy:
            replicas: 5
    # nginx container
    nginx:
        # specifies the latest nginx image
        image: nginx:latest
        # Connects the conf file of the container to the conf file in our folder
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        # start up the nginx only when all api containers have started
        depends_on: 
            - api
        # Connects the port 80 of the nginx container to localhost:8082
        # Port 8082 from your browser now hits the nginx container
        ports: 
            - "8082:80"
        networks: 
            - "api.network"
networks: 
    api.network: